name: Deploy Static HTML to EC2

on:
  push:
    branches:
      - main  # Trigger only on the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clone the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Add the SSH key to the agent
    - name: Add SSH key to agent
      run: |
        eval $(ssh-agent -s)  # Start the SSH agent
        echo "${{ secrets.EC2_SSH_KEY }}" | ssh-add -  # Add the SSH key directly from the secret

    # 3. Copy files to the EC2 server
    - name: Deploy HTML to EC2
      run: |
        scp -o "StrictHostKeyChecking=no" \
          -o "UserKnownHostsFile=/dev/null" \
          -r ./index.html \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }}:${{ secrets.DEPLOY_PATH }}

    # 4. Reload Nginx on the EC2 instance
    - name: Reload Nginx
      run: |
        ssh -o "StrictHostKeyChecking=no" \
          -o "UserKnownHostsFile=/dev/null" \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} \
          "sudo systemctl reload nginx"
