name: Deploy Static HTML to EC2

on:
  push:
    branches:
      - main  # Ejecuta solo en la rama main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Crear el archivo .pem desde el secreto
    - name: Create SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem  # Asegúrate de que la clave tenga permisos adecuados

    # 3. Copia los archivos al servidor EC2
    - name: Deploy HTML to EC2
      run: |
        scp -i ec2_key.pem -o "StrictHostKeyChecking=no" \
          -o "UserKnownHostsFile=/dev/null" \
          -r ./index.html\
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }}:${{ secrets.DEPLOY_PATH }}

    # 4. Reinicia Nginx en la instancia EC2
    - name: Reload Nginx
      run: |
        ssh -i ec2_key.pem -o "StrictHostKeyChecking=no" \
          -o "UserKnownHostsFile=/dev/null" \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} \
          "sudo systemctl reload nginx"

    # 5. Limpia el archivo de la clave
    - name: Clean up
      run: rm -f ec2_key.pem
